### ISSUE TITLE
mbtiles export not exporting anything

### ISSUE THREAD

**Issue by cmyk** [kosmtik/kosmtik#85]
Weird, it's not exporting anything. Do I have the bbox correctly?
--bbox minX,minY,maxX,maxY   BBox to use [Default: project extent]
```
oosm@map:~/carto/kosmtik$ node index.js export ~/carto/map/project.yaml --mapnik-version 3.0.0 --keep-cache --output ~/export/ --bbox 8.9126,47.0027,9.5663,47.6357 --minZoom 3 --maxZoom 16 --scale 2
[Core] Loading config from /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from kosmtik-mbtiles-export
[Core] Loading project from ../map/project.yaml
[Local Config] Patched config from /home/osm/carto/map/localconfig.js
[Core] Generating Mapnik XML…
[Core] Using mapnik version 3.0.0
Exported project to /home/osm/export/
osm@map:~/carto/kosmtik$ 
```

**Comment by yohanboniface** [comment]
Seems you are missing `--format mbtiles`.
Also, I think it expects a files as ouput, so `--output ~/path/to/a/file.mbtiles`

**Comment by cmyk** [comment]
node index.js export ~/carto/map/project.yaml --format mbtiles --mapnik-version 3.0.0 --keep-cache --output ~/export/test.mbtiles --bbox 8.9936,47.097,9.7889,47.5198 --minZoom 3 --maxZoom 16 --scale 2
```
[Export] Processing zoom 12
[Export] 16781312 tiles to process
FATAL ERROR: JS Allocation failed - process out of memory
Aborted
```

**Comment by cmyk** [comment]
@yohanboniface Any tips for this one?

**Comment by yohanboniface** [comment]
Not really :/

Sounds like you are hitting a memory limit, may be Kosmtik fault, but it's really hard to say why without reproducing myself. Have you tried without scale parameter? (not sure it's taken into account, btw).

Also, can you try one zoom level at a time, and see if it passes?

**Comment by cmyk** [comment]
Okay, it seems that the bbox part has issues:

```
node index.js export ~/carto/map/project.yaml --format mbtiles --mapnik-version 3.0.0 --keep-cache --output ~/export/test.mbtiles --bbox 8.9936,47.097,9.7889,47.5198 --minZoom 15 --maxZoom 16
```

It's this bbox:
http://osm.org/go/0C2Q6H?layers=N

It's just export the globe:
```
[Export] Starting MBTiles export to /home/osm/export/test.mbtiles
[Export] Starting MBTiles export, with bounds -180 -85.05112877980659 180 85.05112877980659 and from zoom 15 to 16

/home/osm/carto/kosmtik/node_modules/kosmtik-mbtiles-export/Export.js:30
            if (err) throw err;
                           ^
Error: SQLITE_NOTADB: file is encrypted or is not a database
```

I also tried ```--bbox="8.9936,47.097,9.7889,47.5198"```

**Comment by yohanboniface** [comment]
Good catch! Can you update `kosmtik-mbtiles-export`, it should be fixed now :)

**Comment by cmyk** [comment]
Thanks! Now I get:
```[Export] Starting MBTiles export to /home/osm/export/test.mbtiles
[Export] Starting MBTiles export, with bounds 8.9936 47.097 9.7889 47.5198 and from zoom 15 to 16

/home/osm/carto/kosmtik/node_modules/kosmtik-mbtiles-export/Export.js:30
            if (err) throw err;
                           ^
Error: SQLITE_NOTADB: file is encrypted or is not a database```

The bbox is okay. :+1:

**Comment by cmyk** [comment]
@yohanboniface The export is still taking wrong bbox (i.e. ignoring it and exporting map bounds aka world) with normal non-mbtiles export.
And the mbtiles export is still throwing an error.
We are talking about standard bbox, right? Like here:
http://boundingbox.klokantech.com or here http://wiki.openstreetmap.org/wiki/Bounding_Box
The coordinate pairs would be: longitude latitude (left-bottom) longitude latitude (right-top)
or bbox = min Longitude , min Latitude , max Longitude , max Latitude

**Comment by yohanboniface** [comment]
> The export is still taking wrong bbox (i.e. ignoring it and exporting map bounds aka world) with 
> normal non-mbtiles export.

Needed another fix on the plugin `kosmtik-tiles-export`, please update it.

> And the mbtiles export is still throwing an error.

Which error?

> We are talking about standard bbox, right? Like here:

Well, for a very volatile definition of "standard", yes ;)

See the help:

```
$ kosmtik export --help

Usage: node index.js export [project] [options]

project     Project to export.

Options:
   --mapnik-version             Optional mapnik reference version to be passed to Carto  [3.0.0]
   --proxy                      Optional proxy to use when doing http requests
   --keep-cache                 Do not flush cached metatiles on project load
   --localconfig                Path to local config file [Default: {projectpath}/localconfig.json|.js]
   --output PATH                Filepath to save in
   --width INT                  Width of the export  [1000]
   --height INT                 Height of the export  [1000]
   --bbox minX,minY,maxX,maxY   BBox to use [Default: project extent]
   --scale INT                  Scale the exported image  [1]
   --minZoom INT                Min zoom to be considered for export  [0]
   --maxZoom INT                Max zoom to be considered for export  [18]
   --format FORMAT              Format of the export  [xml]

Export a project
```
